import { RentRollChargeCode } from '../../../models/enums/RentRollChargeCode';


export function matchChargeCode(chargeCode: string): RentRollChargeCode {
  const lowerStr = chargeCode.toLowerCase();
  return DefaultChargeCodeMapping[lowerStr] ?? DefaultChargeCodeRegExMapping.find(([regex]) => {
    return regex.test(lowerStr);
  })?.[1];
}


export const DefaultChargeCodeRegExMapping: [RegExp, RentRollChargeCode][] = [
  [new RegExp('.*(subsidy|sec.{0,2}8|section.?8|sub.?re?nt|rent.?sub).*'), RentRollChargeCode.Subsidy],
  [new RegExp('.*(store?|storage|strg).*'), RentRollChargeCode.Storage],
  [new RegExp('.*(pets[_-]?(re?nt|fee?)|dog|cat|pet[frdmnps]).*'), RentRollChargeCode.PetFees],
  [new RegExp('(\\b| |-|_)pets?(\\b| |-|_)'), RentRollChargeCode.PetFees],
  [new RegExp('.*(\\b| |_)late(fee|\\b| |_).*'), RentRollChargeCode.MiscellaneousOtherIncome],
  [new RegExp('.*applica.*'), RentRollChargeCode.MiscellaneousOtherIncome],
  // eslint-disable-next-line max-len
  [new RegExp('.*(conces|conc?([ -_/]|$)|[-_ ]conc|disc|( |^|-|_)emp[ -_l]|court|conpark|free|vaca|staff|senior|mgmt|mgr|maint|office|ofc|refer|rentemp|rentcon|recon).*'), RentRollChargeCode.Concessions],
  [new RegExp('.*(deposit|forfeiture).*'), RentRollChargeCode.DepositForfeiture],
  // eslint-disable-next-line max-len
  [new RegExp('.*(water|wtr|util|utl|gas|elec|pest|sewer|swr|rubs|reimb|furni|insur|nnn).*'), RentRollChargeCode.ExpenseReimbursements],
  [new RegExp('.*(garag|park|carport|pkg|premium.*pp|prk).*'), RentRollChargeCode.GarageParking],
  [new RegExp('.*(cabl|internet).*'), RentRollChargeCode.CableInternet],
  [new RegExp('.*(valet|trash|trsh|garba).*'), RentRollChargeCode.ValetTrash],
  // eslint-disable-next-line max-len
  [new RegExp('(monthly|actual|apt|apartment|contract|base|current|suite|target|tenant|scheduled|resident|average|collected|unit|effective)(\\b|_| )?rent'), RentRollChargeCode.MonthlyRent],

  [new RegExp('.*(hap|housing|hud)'), RentRollChargeCode.Subsidy],
  [new RegExp('.*dis$'), RentRollChargeCode.Concessions],
  [new RegExp('^(con|emp).*'), RentRollChargeCode.Concessions],
  [new RegExp('^rent(\\b| |_|\\d)'), RentRollChargeCode.MonthlyRent],
  [new RegExp('(\\b| |_|\\d)rent(\\b| |_|\\d)'), RentRollChargeCode.MonthlyRent],
  [new RegExp('rent$'), RentRollChargeCode.MonthlyRent],
  [new RegExp('^re?nt'), RentRollChargeCode.MonthlyRent],

  [new RegExp('.*'), RentRollChargeCode.MiscellaneousOtherIncome],
];

export const DefaultChargeCodeMapping: Record<string, RentRollChargeCode> = {
  'atb-sub': RentRollChargeCode.Subsidy,
  'citysub': RentRollChargeCode.Subsidy,
  'gov_rent': RentRollChargeCode.Subsidy,
  'govh': RentRollChargeCode.Subsidy,
  'haadj': RentRollChargeCode.Subsidy,
  'hda_portion_rent': RentRollChargeCode.Subsidy,
  'lease_expiressec': RentRollChargeCode.Subsidy,
  'pb8sub': RentRollChargeCode.Subsidy,
  'psub': RentRollChargeCode.Subsidy,
  'r-subsdy': RentRollChargeCode.Subsidy,
  'rent8': RentRollChargeCode.Subsidy,
  'resident govt rent': RentRollChargeCode.Subsidy,
  's_rent': RentRollChargeCode.Subsidy,
  's-rent': RentRollChargeCode.Subsidy,
  's-vchr': RentRollChargeCode.Subsidy,
  's8': RentRollChargeCode.Subsidy,
  's8rent': RentRollChargeCode.Subsidy,
  'sec_not_for_site_use_ever': RentRollChargeCode.Subsidy,
  'sub': RentRollChargeCode.Subsidy,
  'sub_sub_lease_fee': RentRollChargeCode.Subsidy,
  'subr': RentRollChargeCode.Subsidy,
  'subr/8': RentRollChargeCode.Subsidy,
  'subre': RentRollChargeCode.Subsidy,
  'subschrg': RentRollChargeCode.Subsidy,
  'subsi': RentRollChargeCode.Subsidy,
  'substitution': RentRollChargeCode.Subsidy,
  'subutil': RentRollChargeCode.Subsidy,
  'subw': RentRollChargeCode.Subsidy,
  'tb8sub': RentRollChargeCode.Subsidy,
  'tbsub': RentRollChargeCode.Subsidy,
  'tensub': RentRollChargeCode.Subsidy,
  'tntsub': RentRollChargeCode.Subsidy,
  'tsub': RentRollChargeCode.Subsidy,
  'vs8': RentRollChargeCode.Subsidy,
  'zsub': RentRollChargeCode.Subsidy,

  'st': RentRollChargeCode.Storage,
  'st1': RentRollChargeCode.Storage,
  'stg': RentRollChargeCode.Storage,
  'sto': RentRollChargeCode.Storage,
  'str': RentRollChargeCode.Storage,
  'stra': RentRollChargeCode.Storage,
  'strtr': RentRollChargeCode.Storage,

  'petchg': RentRollChargeCode.PetFees,
  'petcomp': RentRollChargeCode.PetFees,
  'cmipet': RentRollChargeCode.PetFees,
  'deppet': RentRollChargeCode.PetFees,
  'feepet': RentRollChargeCode.PetFees,
  'mopet': RentRollChargeCode.PetFees,
  'mpet': RentRollChargeCode.PetFees,
  'mpete': RentRollChargeCode.PetFees,
  'npet': RentRollChargeCode.PetFees,
  'nrpet': RentRollChargeCode.PetFees,
  'othpet': RentRollChargeCode.PetFees,
  'penrntin': RentRollChargeCode.PetFees,
  'pent': RentRollChargeCode.PetFees,
  'peters__j_': RentRollChargeCode.PetFees,
  'petesa1': RentRollChargeCode.PetFees,
  'peti': RentRollChargeCode.PetFees,
  'petini': RentRollChargeCode.PetFees,
  'petinonth': RentRollChargeCode.PetFees,
  'rentpet': RentRollChargeCode.PetFees,
  'secpet': RentRollChargeCode.PetFees,
  'spet': RentRollChargeCode.PetFees,

  'app': RentRollChargeCode.MiscellaneousOtherIncome,
  'appf': RentRollChargeCode.MiscellaneousOtherIncome,
  'appfee': RentRollChargeCode.MiscellaneousOtherIncome,
  'appli': RentRollChargeCode.MiscellaneousOtherIncome,
  'applianc': RentRollChargeCode.MiscellaneousOtherIncome,
  'appliance': RentRollChargeCode.MiscellaneousOtherIncome,
  'conappf': RentRollChargeCode.MiscellaneousOtherIncome,

  '1_125_00_empunil': RentRollChargeCode.Concessions,
  '21emp': RentRollChargeCode.Concessions,
  '22crent': RentRollChargeCode.Concessions,
  'add.vapt. allowance': RentRollChargeCode.Concessions,
  'admin_apt': RentRollChargeCode.Concessions,
  'adminemplcred': RentRollChargeCode.Concessions,
  'allow': RentRollChargeCode.Concessions,
  'allowance': RentRollChargeCode.Concessions,
  'apt_1212': RentRollChargeCode.Concessions,
  'avmntcnc': RentRollChargeCode.Concessions,
  'baltimore city rent relief': RentRollChargeCode.Concessions,
  'bdt bad debt write off': RentRollChargeCode.Concessions,
  'caretaker_rent_c': RentRollChargeCode.Concessions,
  'caretaker_rent_cred': RentRollChargeCode.Concessions,
  'cempcons': RentRollChargeCode.Concessions,
  'chg-empo': RentRollChargeCode.Concessions,
  'chg-empr': RentRollChargeCode.Concessions,
  'cncn': RentRollChargeCode.Concessions,
  'cncrg': RentRollChargeCode.Concessions,
  'co6': RentRollChargeCode.Concessions,
  'corprentcredit': RentRollChargeCode.Concessions,
  'covidcnc': RentRollChargeCode.Concessions,
  'cpromo': RentRollChargeCode.Concessions,
  'creditrpt': RentRollChargeCode.Concessions,
  'credits': RentRollChargeCode.Concessions,
  'crent': RentRollChargeCode.Concessions,
  'crtsy': RentRollChargeCode.Concessions,
  'csnrent': RentRollChargeCode.Concessions,
  'd-emp': RentRollChargeCode.Concessions,
  'disrent': RentRollChargeCode.Concessions,
  'dueemp': RentRollChargeCode.Concessions,
  'e_managers_apt': RentRollChargeCode.Concessions,
  'eapt': RentRollChargeCode.Concessions,
  'ebf emp benefit - exp/adj': RentRollChargeCode.Concessions,
  'ebf_emp': RentRollChargeCode.Concessions,
  'econpay': RentRollChargeCode.Concessions,
  'edsc': RentRollChargeCode.Concessions,
  'emc': RentRollChargeCode.Concessions,
  'eunit': RentRollChargeCode.Concessions,
  'fathemp': RentRollChargeCode.Concessions,
  'firrentcredit': RentRollChargeCode.Concessions,
  'govt': RentRollChargeCode.Concessions,
  'grounds_rent_credit': RentRollChargeCode.Concessions,
  'gsremp': RentRollChargeCode.Concessions,
  'hraasst': RentRollChargeCode.Concessions,
  'hrentcr': RentRollChargeCode.Concessions,
  'lessnonr': RentRollChargeCode.Concessions,
  'lrfee lease renewal fee': RentRollChargeCode.Concessions,
  'maempl': RentRollChargeCode.Concessions,
  'mconpro': RentRollChargeCode.Concessions,
  'memp': RentRollChargeCode.Concessions,
  'mil': RentRollChargeCode.Concessions,
  'military': RentRollChargeCode.Concessions,
  'misccred': RentRollChargeCode.Concessions,
  'move-in specials': RentRollChargeCode.Concessions,
  'mstaf': RentRollChargeCode.Concessions,
  'non-rent': RentRollChargeCode.Concessions,
  'nonc': RentRollChargeCode.Concessions,
  'oconcnew': RentRollChargeCode.Concessions,
  'off': RentRollChargeCode.Concessions,
  'offsiteemplcred': RentRollChargeCode.Concessions,
  'onc': RentRollChargeCode.Concessions,
  'onetime': RentRollChargeCode.Concessions,
  'orc': RentRollChargeCode.Concessions,
  'patrol': RentRollChargeCode.Concessions,
  'preemp': RentRollChargeCode.Concessions,
  'pref2': RentRollChargeCode.Concessions,
  'prefemp': RentRollChargeCode.Concessions,
  'prefempl': RentRollChargeCode.Concessions,
  'premp': RentRollChargeCode.Concessions,
  'prfempl': RentRollChargeCode.Concessions,
  'r-eeaptm': RentRollChargeCode.Concessions,
  'r-renew': RentRollChargeCode.Concessions,
  'raconcot': RentRollChargeCode.Concessions,
  'raemplea': RentRollChargeCode.Concessions,
  'raempmai': RentRollChargeCode.Concessions,
  'rconreoc': RentRollChargeCode.Concessions,
  'recinc': RentRollChargeCode.Concessions,
  'recurr': RentRollChargeCode.Concessions,
  'reduction': RentRollChargeCode.Concessions,
  'renew': RentRollChargeCode.Concessions,
  'rent_credits_receipt': RentRollChargeCode.Concessions,
  'rentc': RentRollChargeCode.Concessions,
  'renw': RentRollChargeCode.Concessions,
  'renwone': RentRollChargeCode.Concessions,
  'resconce': RentRollChargeCode.Concessions,
  'rmain': RentRollChargeCode.Concessions,
  'rrc': RentRollChargeCode.Concessions,
  'rrrentcr': RentRollChargeCode.Concessions,
  'special': RentRollChargeCode.Concessions,
  'storemp': RentRollChargeCode.Concessions,
  'student': RentRollChargeCode.Concessions,
  'super unit cred': RentRollChargeCode.Concessions,
  'super_unit_cred': RentRollChargeCode.Concessions,
  'tconee': RentRollChargeCode.Concessions,
  'tcsb': RentRollChargeCode.Concessions,
  'teacher': RentRollChargeCode.Concessions,
  'temp': RentRollChargeCode.Concessions,
  'temp_garage_re': RentRollChargeCode.Concessions,
  'temrentcredit': RentRollChargeCode.Concessions,
  'turnrentcredit': RentRollChargeCode.Concessions,
  'uotax': RentRollChargeCode.Concessions,
  'upco': RentRollChargeCode.Concessions,
  'useocc': RentRollChargeCode.Concessions,
  'wconvpck': RentRollChargeCode.Concessions,
  'write off': RentRollChargeCode.Concessions,
  'xempprop': RentRollChargeCode.Concessions,
  'xonetime': RentRollChargeCode.Concessions,
  'xrecurr': RentRollChargeCode.Concessions,
  'zresref': RentRollChargeCode.Concessions,

  'dep': RentRollChargeCode.DepositForfeiture,
  'nonrfdep': RentRollChargeCode.DepositForfeiture,
  'secdep': RentRollChargeCode.DepositForfeiture,

  'adminrub': RentRollChargeCode.ExpenseReimbursements,
  'cam': RentRollChargeCode.ExpenseReimbursements,
  'conval': RentRollChargeCode.ExpenseReimbursements,
  'conwatr': RentRollChargeCode.ExpenseReimbursements,
  'd_damages_other': RentRollChargeCode.ExpenseReimbursements,
  'drainage': RentRollChargeCode.ExpenseReimbursements,
  'mvwaste': RentRollChargeCode.ExpenseReimbursements,
  'opexp': RentRollChargeCode.ExpenseReimbursements,
  'property tax billback': RentRollChargeCode.ExpenseReimbursements,
  'r-watsvc': RentRollChargeCode.ExpenseReimbursements,
  're-tax': RentRollChargeCode.ExpenseReimbursements,
  'rsew': RentRollChargeCode.ExpenseReimbursements,
  'rtaxrent': RentRollChargeCode.ExpenseReimbursements,
  'rub': RentRollChargeCode.ExpenseReimbursements,
  'rub charge*': RentRollChargeCode.ExpenseReimbursements,
  'rubbish': RentRollChargeCode.ExpenseReimbursements,
  'rubnet': RentRollChargeCode.ExpenseReimbursements,
  'ruwatsew': RentRollChargeCode.ExpenseReimbursements,
  'rwat': RentRollChargeCode.ExpenseReimbursements,
  'sew': RentRollChargeCode.ExpenseReimbursements,
  'strwdw/d': RentRollChargeCode.ExpenseReimbursements,
  'tax': RentRollChargeCode.ExpenseReimbursements,
  'ur': RentRollChargeCode.ExpenseReimbursements,
  'urwt': RentRollChargeCode.ExpenseReimbursements,
  'utfee': RentRollChargeCode.ExpenseReimbursements,
  'utitiy_administrative_fee': RentRollChargeCode.ExpenseReimbursements,
  'vaterremo': RentRollChargeCode.ExpenseReimbursements,
  'viate mb': RentRollChargeCode.ExpenseReimbursements,
  'vwast': RentRollChargeCode.ExpenseReimbursements,
  'w_/s_rent': RentRollChargeCode.ExpenseReimbursements,
  'w/s': RentRollChargeCode.ExpenseReimbursements,
  'wat': RentRollChargeCode.ExpenseReimbursements,
  'watr': RentRollChargeCode.ExpenseReimbursements,
  'watsew': RentRollChargeCode.ExpenseReimbursements,
  'wdrn': RentRollChargeCode.ExpenseReimbursements,
  'ws': RentRollChargeCode.ExpenseReimbursements,

  'carp': RentRollChargeCode.GarageParking,
  'carpo': RentRollChargeCode.GarageParking,
  'carpt': RentRollChargeCode.GarageParking,
  'chg-gar': RentRollChargeCode.GarageParking,
  'congarg': RentRollChargeCode.GarageParking,
  'cportrnt': RentRollChargeCode.GarageParking,
  'crprt': RentRollChargeCode.GarageParking,
  'gar': RentRollChargeCode.GarageParking,
  'gara': RentRollChargeCode.GarageParking,
  'garapt': RentRollChargeCode.GarageParking,
  'garconc': RentRollChargeCode.GarageParking,
  'gardet': RentRollChargeCode.GarageParking,
  'garent': RentRollChargeCode.GarageParking,
  'garg': RentRollChargeCode.GarageParking,
  'gargrent': RentRollChargeCode.GarageParking,
  'garp': RentRollChargeCode.GarageParking,
  'garpot': RentRollChargeCode.GarageParking,
  'garr': RentRollChargeCode.GarageParking,
  'garrent': RentRollChargeCode.GarageParking,
  'gratgar': RentRollChargeCode.GarageParking,
  'grginc': RentRollChargeCode.GarageParking,
  'grscon': RentRollChargeCode.GarageParking,
  'hcar': RentRollChargeCode.GarageParking,
  'hgar': RentRollChargeCode.GarageParking,
  'mgrpking': RentRollChargeCode.GarageParking,
  'monthly_carp': RentRollChargeCode.GarageParking,
  'mscgar': RentRollChargeCode.GarageParking,
  'par': RentRollChargeCode.GarageParking,
  'pgar': RentRollChargeCode.GarageParking,
  'r-congar': RentRollChargeCode.GarageParking,
  'rentgrg': RentRollChargeCode.GarageParking,
  'reserved_covere': RentRollChargeCode.GarageParking,
  'rv': RentRollChargeCode.GarageParking,

  '00_renl': RentRollChargeCode.MonthlyRent,
  '1_330_00_mtm': RentRollChargeCode.MonthlyRent,
  '100\nrented': RentRollChargeCode.MonthlyRent,
  '100% rented': RentRollChargeCode.MonthlyRent,
  '100%_rented': RentRollChargeCode.MonthlyRent,
  '2ocup': RentRollChargeCode.MonthlyRent,
  'actual': RentRollChargeCode.MonthlyRent,
  'al': RentRollChargeCode.MonthlyRent,
  'amount_monthly': RentRollChargeCode.MonthlyRent,
  'average leased': RentRollChargeCode.MonthlyRent,
  'avg_monthly_rate_assuming_80%_occ_': RentRollChargeCode.MonthlyRent,
  'corrected_rental': RentRollChargeCode.MonthlyRent,
  'doubleoc': RentRollChargeCode.MonthlyRent,
  'gain/_loss_to_lease': RentRollChargeCode.MonthlyRent,
  'hipresre': RentRollChargeCode.MonthlyRent,
  'home': RentRollChargeCode.MonthlyRent,
  'home_rental': RentRollChargeCode.MonthlyRent,
  'house_rental_(fv': RentRollChargeCode.MonthlyRent,
  'in-place': RentRollChargeCode.MonthlyRent,
  'lease_actual': RentRollChargeCode.MonthlyRent,
  'loss_to_market': RentRollChargeCode.MonthlyRent,
  'lot': RentRollChargeCode.MonthlyRent,
  'monthly': RentRollChargeCode.MonthlyRent,
  'rc': RentRollChargeCode.MonthlyRent,
  'rd_renl': RentRollChargeCode.MonthlyRent,
  'ren': RentRollChargeCode.MonthlyRent,
  'ren!': RentRollChargeCode.MonthlyRent,
  'reni': RentRollChargeCode.MonthlyRent,
  'renl': RentRollChargeCode.MonthlyRent,
  'ront': RentRollChargeCode.MonthlyRent,
  'rtbr': RentRollChargeCode.MonthlyRent,
  'spc/newrental': RentRollChargeCode.MonthlyRent,
  'suite_details:_rentable_suites': RentRollChargeCode.MonthlyRent,
  'tenant portion': RentRollChargeCode.MonthlyRent,
  'tenant_portion': RentRollChargeCode.MonthlyRent,

  'ugarbr': RentRollChargeCode.ValetTrash,
  'rtra': RentRollChargeCode.ValetTrash,
  'rubstras': RentRollChargeCode.ValetTrash,
  'vlt': RentRollChargeCode.ValetTrash,
  'ugarb': RentRollChargeCode.ValetTrash,
  'tshfee': RentRollChargeCode.ValetTrash,
  'valtsh': RentRollChargeCode.ValetTrash,
  'env_environmental_disposal_fee': RentRollChargeCode.ValetTrash,
  'env_environmental_disposal': RentRollChargeCode.ValetTrash,
  'valtra': RentRollChargeCode.ValetTrash,
  'ft_furniture_removal': RentRollChargeCode.ValetTrash,
  'val': RentRollChargeCode.ValetTrash,
  'valreim': RentRollChargeCode.ValetTrash,
};
