export const OtherChargeCodes = {
  'rent': true,
  'total': true,
  'trash': true,
  'extrmfee': true,
  'insurance': true,
  'petfee': true,
  'resident rent': true,
  'rnt': true,
  'cable': true,
  'rubs': true,
  'garage': true,
  'petrent': true,
  'trashex': true,
  'rubtsh': true,
  'subsidy subrent': true,
  'rub': true,
  'billing fee': true,
  'elec': true,
  'r-rent': true,
  'gas': true,
  'conc-bonding': true,
  'cable/internet': true,
  'utility': true,
  'pestcontrolreimb': true,
  'amenity premium': true,
  'pst': true,
  'sewer': true,
  'pest control': true,
  'valettrash': true,
  'water': true,
  'trash fee': true,
  'conrent': true,
  'conc': true,
  'trash-pu': true,
  'pest': true,
  'trshr': true,
  'cha-rent': true,
  'prefrent': true,
  'chg-rins': true,
  'hoa': true,
  'subrent': true,
  'r -rubs': true,
  'pet rent': true,
  'csrenew': true,
  'mtom': true,
  'gar': true,
  'conwatr': true,
  'trashreimb': true,
  'r-rubs': true,
  'concession': true,
  'r -rent': true,
  'resident pestcontrolreimb': true,
  'locpr': true,
  'security': true,
  'mutility': true,
  'petr': true,
  'mci': true,
  'hud': true,
  'r-trash': true,
  'rconc': true,
  'insrent': true,
  'csmove': true,
  'conc/recurring': true,
  'w/d': true,
  'r- trash': true,
  'park': true,
  'pet': true,
  'storage': true,
  'resident petrent': true,
  'ptr': true,
  'mtm': true,
  'parking': true,
  'r -trash': true,
  'washdry': true,
  'xrecurr': true,
  'waterreimb': true,
  'washer': true,
  'nytax': true,
  'carport': true,
  'disc': true,
  'scrie': true,
  'prnt': true,
  'pestctrl': true,
  'cvpkg': true,
  'petfees': true,
  'rvoucher': true,
  'r - trash': true,
  'rent discount': true,
  'conc/specl': true,
  'cmth': true,
  'garbage': true,
  'conc/spec': true,
  'insure': true,
  'resident conc/retail': true,
  'emplcred': true,
  'resident carport': true,
  'stor': true,
  'garag': true,
  'pep': true,
  'r-petfee': true,
  'grt': true,
  'wash/dry': true,
  'resident utilreimb': true,
  'premium': true,
  'short': true,
  'hraasst': true,
  'petf': true,
  'prefemployer disc': true,
  'renewal conc': true,
  'rent/ah': true,
  'resident wash/dry': true,
  'chg-petr': true,
  'short term premium': true,
  'conc/one': true,
  'aircond': true,
  'chg-gar': true,
  'subsidy': true,
  'prent': true,
  'loc': true,
  'residentrent': true,
  'r- rubs': true,
  'rentersins': true,
  'con-pepm': true,
  'misc': true,
  'preferredemp': true,
  'r -petfee': true,
  'subsidy utac': true,
  'r - rubs': true,
  'milcs': true,
  'mpet': true,
  'sti': true,
  'model': true,
  'ubtrash': true,
  'r- rent': true,
  'r-petmon': true,
  'r-subsdy': true,
  'stp': true,
  'utac': true,
  'r - rent': true,
  'accon': true,
  'vacadmin': true,
  'mtmfee': true,
  'storage unit': true,
  'shorttermleasefee': true,
  'ubpest': true,
  'petdep': true,
  'pestfee': true,
  'telecom': true,
  'resident shortterm': true,
  'mcable': true,
  'ws': true,
  'resident conc/pro': true,
  'senior': true,
  'rubsfee': true,
  'drie': true,
  'conc-recurring': true,
  'garage rental income': true,
  'resident conc/renew': true,
  'housing housing': true,
  'concs': true,
  'rorubs': true,
  'cnlr': true,
  'furn': true,
  'r -mtm': true,
  'disc_emp': true,
  'sto': true,
  'resident mtom': true,
  'wsh': true,
  'mrubs': true,
  'conpetrt': true,
  'ren t': true,
  'r- petfee': true,
  'mvwaste': true,
  'utl': true,
  'r -prem': true,
  'retrash': true,
  'resident': true,
  'repay': true,
  'mic': true,
  'mm': true,
  'premshort': true,
  'resident maintunit': true,
  'conpetf': true,
  'discount': true,
  'garag e': true,
  'resident storage': true,
  'rurent': true,
  'rent .': true,
  'ugarbr': true,
  'resident petfee': true,
  'st': true,
  'rrconc': true,
  'trf': true,
  'disc_mil': true,
  'con': true,
  't-rubs': true,
  's-rubs': true,
  'rentins': true,
  'emplydis': true,
  'caole': true,
  'ropetfee': true,
  'residentpetrent': true,
  'resident waterreimb': true,
  'r -mum': true,
  'storageunit': true,
  'highriskfee': true,
  'residentcarport': true,
  'resident corp income': true,
  'erent': true,
  'upgradefee': true,
  'noproratecred': true,
  'misccred': true,
  'military': true,
  'waterreima': true,
  'p': true,
  'torent': true,
  'resident parking': true,
  'resident furn': true,
  'waterreimo': true,
  'referral': true,
  'shortterm': true,
  't -rent': true,
  'corpaptrevenue': true,
  'resident modelunit': true,
  't - trash': true,
  'xmgmt': true,
  'p- petfee': true,
  'petd': true,
  'onetimepetfee': true,
  'r -empl- z': true,
  'sprgm': true,
  's-trash': true,
  'innt': true,
  'txxcourt': true,
  'furent': true,
  'r-petree': true,
  'cor': true,
  'r -petree': true,
  'empld': true,
  'vaterreimo': true,
  'vaterreime': true,
  'vaterreimd': true,
  'int': true,
  'cablecomm': true,
  'intupgrade': true,
  'r rent': true,
  'conemp': true,
  'hap': true,
  'furnrentalrev': true,
  'adminfee': true,
  'corprent': true,
  'deposit': true,
  'p -mtm': true,
  '.pet rent': true,
  'empo': true,
  'resident super unit cred': true,
  'reprem': true,
  'mmodel': true,
  'resident emplcred': true,
  'conospec': true,
  'r-pettee': true,
  'shi': true,
  'corprentcredit': true,
  'concothr': true,
  'vacmodel': true,
  'appfee': true,
  'secdep': true,
  'r-mgtoff': true,
  'emplo': true,
  'waterreimd': true,
  'resident fines': true,
  'rubs - pestcontrolreimb': true,
  'courtesy': true,
  'mci-ph': true,
  'rent ...': true,
  'r -wash': true,
  't -empl- z': true,
  'upgrade': true,
  'other': true,
  'xleas': true,
  'empfree': true,
  'conconc': true,
  'dmg': true,
  'orent': true,
  't-petfee': true,
  'empconc': true,
  'resident ofcrcred': true,
  'maint': true,
  'remotes': true,
  't - rubs': true,
  'r - petfee': true,
  'r - pettee': true,
  'empl free rent': true,
  'courtesyofficer': true,
  't-rent': true,
  'r - prem': true,
  'stl': true,
  'r-empl- z': true,
  'r-empl- e': true,
  'vtility': true,
  '---"- rent': true,
  'r -emple': true,
  'util': true,
  'bent': true,
  'ofcr': true,
  'chg-util': true,
  'r- petree': true,
  're nt': true,
  'pddiscount': true,
  'r -pettee': true,
  'con-rins': true,
  'st.prem .': true,
  'concessions': true,
  'yyaterreimb': true,
  'ubwaterb': true,
  'exterminating recovery': true,
  'concess': true,
  'fathemp': true,
  'renttotal': true,
  's-rent': true,
  'resident damages': true,
  'emplcredloss': true,
  'admin': true,
  'contrash': true,
  'xonetime': true,
  'subsidy rent': true,
  'monthtomonth': true,
  'ofcrcred': true,
  'petfeenonrefund': true,
  'r-mtm': true,
  'chg-mtm': true,
  'short term fee': true,
  'uconc': true,
  'employee': true,
  'pool': true,
  'mmtm': true,
  'emp': true,
  'conc-one time': true,
  '* total:': true,
  'garagerental income': true,
  'vaterreimb': true,
  'mt': true,
  'cnmi': true,
  'mnt': true,
  'repetfee': true,
  'chg-empr': true,
  'mconcot': true,
  'chg-empo': true,
  'lock off premium': true,
  'shrtterm': true,
  'nonrev': true,
  'waterreime': true,
  'empl rent discount': true,
  'mispec': true,
  'con-mon': true,
  'housing': true,
  'waste': true,
  'mil': true,
  'ufutil': true,
  'resident conc/emp': true,
  't -rubs': true,
  't -petfee': true,
  'chg-stp': true,
  'keys': true,
  'empdisc': true,
  'empdis': true,
  'r. petfee': true,
  'resident conc/specl': true,
  'empl': true,
  'resident rent/ah': true,
  'turn damage': true,
  'coa': true,
  'bmr': true,
  'water charge': true,
  'empcourt': true,
  'r.petfee': true,
  'turn cleaning': true,
  'resident garage': true,
  'modelcon': true,
  'tota !': true,
  't - rent': true,
  'short term lease fee': true,
  'r-stp': true,
  'rent/hud': true,
  'teacher': true,
  'resident electricreimb': true,
  'resident conc/other': true,
  'chg-stor': true,
  'shop': true,
  'pref': true,
  'elect': true,
  'petren': true,
  'renew': true,
};
