export const PayrollLineItems = new Set([
  'less comped units emp',
  'guest suite',
  'apartments',
  'less employee housing discount',
  'employee concession',
  'employee apt discount',
  'model employee suite office',
  'model employee unit',
  'staff owner unit',
  'model employee unit',
  'oper maint rent free unit',
  'employee units model',
  'less employee apartments',
  'employee unit',
  'less employee units',
  'maintenance rent free unit',
  'maintenance rent free unit',
  'employee allowance',
  'security units',
  'courtesy officer units',
  'employee units',
  'model office shop employee',
  'courtesy officer',
  'cares team',
  'employee bldg attendant apartment',
  'employee bldg attendant ap',
  'employee bldg attendant apartment',
  'superintendent unit rent allowance',
  'employee rent free unit',
  'employee units',
  'employee discounts',
  'room rental revenue adm',
  'models employee concessio',
  'rent loss employee units',
  'rent loss employee units',
  'employee unit discount',
  'security free rent units',
  'security rent free units',
  'non rent rev employee unit',
  'manager rent free unit',
  'employee apartment concession',
  'discounts emp model other',
  'conces employee free',
  'employee concession',
]);
